language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database goodbrews_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
