language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/auth.yml.sample config/auth.yml
  - cp config/database.yml.sample config/database.yml
  - cp config/redis.yml.sample config/redis.yml
  - cp config/initializers/secret_token.rb.sample config/initializers/secret_token.rb
  - psql -c 'create database goodbrews_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
notifications:
  email:
    recipients:
      - david@davidcelis.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#goodbrews"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch}@%{commit} by %{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build details: %{build_url}"
