defaults: &defaults
  uri:  <%= uri = URI.parse ENV.fetch('REDIS_URL', 'redis://localhost:6379') %>
  host: <%= uri.host %>
  port: <%= uri.port %>
  password: <%= uri.password %>
  db: 0

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 15

staging:
  <<: *defaults

production:
  <<: *defaults
